class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://apps.kde.org/kcachegrind/"
  url "https://download.kde.org/stable/release-service/26.08.2/src/kcachegrind-26.08.2.tar.xz"
  sha256 "641a809f7ba5a97637820222b6c7fc639d7bc5d4a1036c69c4886823edb0670a"
  license "GPL-2.0-or-later"
  head "https://invent.kde.org/sdk/kcachegrind.git", branch: "master"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    root_url "https://github.com/happyendingll/intel-bottles/releases/download/bottles-2"
    sha256 cellar: :any, sequoia: "fc2d3ef16bf50ea74acf1d6fff3a8a6faa1e9c3d57e69c727b937156c7b6a60b"
  end

  depends_on "graphviz"
  depends_on "qtbase"

  deny_network_access!

  def install
    args = %w[-config release]
    if OS.mac?
      spec = (ENV.compiler == :clang) ? "macx-clang" : "macx-g++"
      args += %W[-spec #{spec}]
    end

    qt = Formula["qtbase"]
    system qt.opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end

  test do
    (testpath/"callgrind.out.1").write <<~EOS
      # callgrind format
      version: 1
      creator: homebrew
      pid: 1
      cmd: ./test
      events: Ir
      fl=test.c
      fn=main
      3 10
      cfn=foo
      calls=1 8
      4 25
      fn=foo
      8 25
    EOS

    ENV["QT_QPA_PLATFORM"] = "offscreen"
    ENV["XDG_CONFIG_HOME"] = testpath/".config"
    pid = spawn bin/"qcachegrind", testpath/"callgrind.out.1"
    begin
      if OS.linux?
        # A successfully loaded profile is added to the recent files list
        conf = testpath/".config/kde.org/QCachegrind.conf"
        30.times do
          break if conf.exist? && conf.read.include?("callgrind.out.1")

          sleep 1
        end
        assert_match "#{testpath}/callgrind.out.1", conf.read
      else
        sleep 5
      end
      assert_nil Process.wait(pid, Process::WNOHANG), "qcachegrind exited unexpectedly"
    ensure
      Process.kill("TERM", pid)
      Process.wait(pid)
    end
  end
end
